---
services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.4.5
    environment:
      KC_HOSTNAME: keycloak 
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info
      KC_HTTPS_CERTIFICATE_FILE: /etc/x509/https/tls.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/x509/https/tls.key
    command: ["start-dev", "--http-port", "8080", "--https-port", "8443"]
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9000:9000"
    networks:
      - kind
    volumes:
      - ./keycloak.crt:/etc/x509/https/tls.crt
      - ./keycloak.key:/etc/x509/https/tls.key

networks:
  kind:
    external: true
