kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraMounts:
    - containerPath: /etc/ssl/certs/keycloak.crt
      hostPath: ./keycloak.crt 
kubeadmConfigPatches:
- |
  kind: ClusterConfiguration
  apiServer:
    extraArgs:
      oidc-issuer-url: "https://keycloak:8443/realms/nightosphere"
      oidc-client-id: "kubeosphere"
      oidc-username-claim: "email"
      oidc-groups-claim: "groups"
      oidc-ca-file: /etc/ssl/certs/keycloak.crt
